project:
  type: book

book:
  title: "Data and Visualization in R"
  subtitle: "A practical guide for social scientists"
  author:
    - name: Alfredo Hernandez Sanchez, PhD
      orcid: 0000-0001-7643-249X
      url: www.alfredohs.com
  date: "today"
  reader-mode: true
  repo-url: "https://github.com/alfredo-hs/dviz_book"
  repo-actions: [issue]
  sidebar: 
    logo: "resources/icon.png"
  chapters:
    - index.qmd
    - intro.qmd
    - ggbasics.qmd
    # - maps/index.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt

execute:
  warning: false
  message: false
  
editor: source

